[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sysdiagnose"
version = "0.1.0"
description = "A tool for sysdiagnose parsing and analysis"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.11"
license = {text = "EUPL-1.2"}
authors = [
  { name="EC-DIGIT-CSIRC", email="EC-DIGIT-CSIRC@ec.europa.eu" },
]
maintainers = [
  { name="EC-DIGIT-CSIRC", email="EC-DIGIT-CSIRC@ec.europa.eu" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: EUPL 1.2",
    "Operating System :: OS Independent",
]
keywords = ["sysdiagnose", "analysis", "parsing", "iOS", "apple", "malware", "forensics"]
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://github.com/EC-DIGIT-CSIRC/sysdiagnose"
Issues = "https://github.com/EC-DIGIT-CSIRC/sysdiagnose/issues"

[project.scripts]
sysdiag = "sysdiagnose.main:main"
saf = "sysdiagnose.main:main"

# Define dependencies dynamically
[tool.hatch.metadata.hooks.requirements]
path = "requirements.txt"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/.vscode",
]

[tool.hatch.build.targets.wheel]
packages = ["src/sysdiagnose"]